// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/ua_kernel/v1/syscall.proto

package ua_kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_EmitEvent_FullMethodName      = "/ua_kernel.v1.EventService/EmitEvent"
	EventService_SubscribeLocal_FullMethodName = "/ua_kernel.v1.EventService/SubscribeLocal"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService handles event routing between the kernel and UMCs
type EventServiceClient interface {
	// EmitEvent publishes an event to the kernel event bus
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error)
	// SubscribeLocal subscribes to local events (server-streaming)
	SubscribeLocal(ctx context.Context, in *SubscribeLocalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalEvent], error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitEventResponse)
	err := c.cc.Invoke(ctx, EventService_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SubscribeLocal(ctx context.Context, in *SubscribeLocalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], EventService_SubscribeLocal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeLocalRequest, LocalEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeLocalClient = grpc.ServerStreamingClient[LocalEvent]

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService handles event routing between the kernel and UMCs
type EventServiceServer interface {
	// EmitEvent publishes an event to the kernel event bus
	EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error)
	// SubscribeLocal subscribes to local events (server-streaming)
	SubscribeLocal(*SubscribeLocalRequest, grpc.ServerStreamingServer[LocalEvent]) error
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedEventServiceServer) SubscribeLocal(*SubscribeLocalRequest, grpc.ServerStreamingServer[LocalEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeLocal not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SubscribeLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLocalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).SubscribeLocal(m, &grpc.GenericServerStream[SubscribeLocalRequest, LocalEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeLocalServer = grpc.ServerStreamingServer[LocalEvent]

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitEvent",
			Handler:    _EventService_EmitEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeLocal",
			Handler:       _EventService_SubscribeLocal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}

const (
	ExecService_RunProcess_FullMethodName        = "/ua_kernel.v1.ExecService/RunProcess"
	ExecService_StopProcess_FullMethodName       = "/ua_kernel.v1.ExecService/StopProcess"
	ExecService_InspectProcess_FullMethodName    = "/ua_kernel.v1.ExecService/InspectProcess"
	ExecService_AllocateResources_FullMethodName = "/ua_kernel.v1.ExecService/AllocateResources"
)

// ExecServiceClient is the client API for ExecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExecService provides process execution authority
type ExecServiceClient interface {
	// RunProcess executes a process with the given parameters
	RunProcess(ctx context.Context, in *RunProcessRequest, opts ...grpc.CallOption) (*RunProcessResponse, error)
	// StopProcess terminates a running process
	StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessResponse, error)
	// InspectProcess retrieves process status and metadata
	InspectProcess(ctx context.Context, in *InspectProcessRequest, opts ...grpc.CallOption) (*InspectProcessResponse, error)
	// AllocateResources allocates resource limits for a process
	AllocateResources(ctx context.Context, in *AllocateResourcesRequest, opts ...grpc.CallOption) (*AllocateResourcesResponse, error)
}

type execServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecServiceClient(cc grpc.ClientConnInterface) ExecServiceClient {
	return &execServiceClient{cc}
}

func (c *execServiceClient) RunProcess(ctx context.Context, in *RunProcessRequest, opts ...grpc.CallOption) (*RunProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunProcessResponse)
	err := c.cc.Invoke(ctx, ExecService_RunProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execServiceClient) StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProcessResponse)
	err := c.cc.Invoke(ctx, ExecService_StopProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execServiceClient) InspectProcess(ctx context.Context, in *InspectProcessRequest, opts ...grpc.CallOption) (*InspectProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectProcessResponse)
	err := c.cc.Invoke(ctx, ExecService_InspectProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execServiceClient) AllocateResources(ctx context.Context, in *AllocateResourcesRequest, opts ...grpc.CallOption) (*AllocateResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResourcesResponse)
	err := c.cc.Invoke(ctx, ExecService_AllocateResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecServiceServer is the server API for ExecService service.
// All implementations must embed UnimplementedExecServiceServer
// for forward compatibility.
//
// ExecService provides process execution authority
type ExecServiceServer interface {
	// RunProcess executes a process with the given parameters
	RunProcess(context.Context, *RunProcessRequest) (*RunProcessResponse, error)
	// StopProcess terminates a running process
	StopProcess(context.Context, *StopProcessRequest) (*StopProcessResponse, error)
	// InspectProcess retrieves process status and metadata
	InspectProcess(context.Context, *InspectProcessRequest) (*InspectProcessResponse, error)
	// AllocateResources allocates resource limits for a process
	AllocateResources(context.Context, *AllocateResourcesRequest) (*AllocateResourcesResponse, error)
	mustEmbedUnimplementedExecServiceServer()
}

// UnimplementedExecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecServiceServer struct{}

func (UnimplementedExecServiceServer) RunProcess(context.Context, *RunProcessRequest) (*RunProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunProcess not implemented")
}
func (UnimplementedExecServiceServer) StopProcess(context.Context, *StopProcessRequest) (*StopProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProcess not implemented")
}
func (UnimplementedExecServiceServer) InspectProcess(context.Context, *InspectProcessRequest) (*InspectProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectProcess not implemented")
}
func (UnimplementedExecServiceServer) AllocateResources(context.Context, *AllocateResourcesRequest) (*AllocateResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateResources not implemented")
}
func (UnimplementedExecServiceServer) mustEmbedUnimplementedExecServiceServer() {}
func (UnimplementedExecServiceServer) testEmbeddedByValue()                     {}

// UnsafeExecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecServiceServer will
// result in compilation errors.
type UnsafeExecServiceServer interface {
	mustEmbedUnimplementedExecServiceServer()
}

func RegisterExecServiceServer(s grpc.ServiceRegistrar, srv ExecServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecService_ServiceDesc, srv)
}

func _ExecService_RunProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServiceServer).RunProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecService_RunProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServiceServer).RunProcess(ctx, req.(*RunProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecService_StopProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServiceServer).StopProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecService_StopProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServiceServer).StopProcess(ctx, req.(*StopProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecService_InspectProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServiceServer).InspectProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecService_InspectProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServiceServer).InspectProcess(ctx, req.(*InspectProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecService_AllocateResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServiceServer).AllocateResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecService_AllocateResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServiceServer).AllocateResources(ctx, req.(*AllocateResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecService_ServiceDesc is the grpc.ServiceDesc for ExecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.ExecService",
	HandlerType: (*ExecServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunProcess",
			Handler:    _ExecService_RunProcess_Handler,
		},
		{
			MethodName: "StopProcess",
			Handler:    _ExecService_StopProcess_Handler,
		},
		{
			MethodName: "InspectProcess",
			Handler:    _ExecService_InspectProcess_Handler,
		},
		{
			MethodName: "AllocateResources",
			Handler:    _ExecService_AllocateResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}

const (
	IdentityService_GetNodeIdentity_FullMethodName       = "/ua_kernel.v1.IdentityService/GetNodeIdentity"
	IdentityService_SignPayload_FullMethodName           = "/ua_kernel.v1.IdentityService/SignPayload"
	IdentityService_VerifyTrust_FullMethodName           = "/ua_kernel.v1.IdentityService/VerifyTrust"
	IdentityService_IssueLocalCertificate_FullMethodName = "/ua_kernel.v1.IdentityService/IssueLocalCertificate"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService manages node identity and cryptographic operations
type IdentityServiceClient interface {
	// GetNodeIdentity returns the node's identity information
	GetNodeIdentity(ctx context.Context, in *GetNodeIdentityRequest, opts ...grpc.CallOption) (*GetNodeIdentityResponse, error)
	// SignPayload signs arbitrary data with the node's private key
	SignPayload(ctx context.Context, in *SignPayloadRequest, opts ...grpc.CallOption) (*SignPayloadResponse, error)
	// VerifyTrust verifies a signature against trusted certificates
	VerifyTrust(ctx context.Context, in *VerifyTrustRequest, opts ...grpc.CallOption) (*VerifyTrustResponse, error)
	// IssueLocalCertificate generates a local certificate for a component
	IssueLocalCertificate(ctx context.Context, in *IssueLocalCertificateRequest, opts ...grpc.CallOption) (*IssueLocalCertificateResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetNodeIdentity(ctx context.Context, in *GetNodeIdentityRequest, opts ...grpc.CallOption) (*GetNodeIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetNodeIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SignPayload(ctx context.Context, in *SignPayloadRequest, opts ...grpc.CallOption) (*SignPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignPayloadResponse)
	err := c.cc.Invoke(ctx, IdentityService_SignPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyTrust(ctx context.Context, in *VerifyTrustRequest, opts ...grpc.CallOption) (*VerifyTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTrustResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) IssueLocalCertificate(ctx context.Context, in *IssueLocalCertificateRequest, opts ...grpc.CallOption) (*IssueLocalCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueLocalCertificateResponse)
	err := c.cc.Invoke(ctx, IdentityService_IssueLocalCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService manages node identity and cryptographic operations
type IdentityServiceServer interface {
	// GetNodeIdentity returns the node's identity information
	GetNodeIdentity(context.Context, *GetNodeIdentityRequest) (*GetNodeIdentityResponse, error)
	// SignPayload signs arbitrary data with the node's private key
	SignPayload(context.Context, *SignPayloadRequest) (*SignPayloadResponse, error)
	// VerifyTrust verifies a signature against trusted certificates
	VerifyTrust(context.Context, *VerifyTrustRequest) (*VerifyTrustResponse, error)
	// IssueLocalCertificate generates a local certificate for a component
	IssueLocalCertificate(context.Context, *IssueLocalCertificateRequest) (*IssueLocalCertificateResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) GetNodeIdentity(context.Context, *GetNodeIdentityRequest) (*GetNodeIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) SignPayload(context.Context, *SignPayloadRequest) (*SignPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignPayload not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyTrust(context.Context, *VerifyTrustRequest) (*VerifyTrustResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTrust not implemented")
}
func (UnimplementedIdentityServiceServer) IssueLocalCertificate(context.Context, *IssueLocalCertificateRequest) (*IssueLocalCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLocalCertificate not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetNodeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetNodeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetNodeIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetNodeIdentity(ctx, req.(*GetNodeIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SignPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SignPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SignPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SignPayload(ctx, req.(*SignPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyTrust(ctx, req.(*VerifyTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_IssueLocalCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueLocalCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).IssueLocalCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_IssueLocalCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).IssueLocalCertificate(ctx, req.(*IssueLocalCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeIdentity",
			Handler:    _IdentityService_GetNodeIdentity_Handler,
		},
		{
			MethodName: "SignPayload",
			Handler:    _IdentityService_SignPayload_Handler,
		},
		{
			MethodName: "VerifyTrust",
			Handler:    _IdentityService_VerifyTrust_Handler,
		},
		{
			MethodName: "IssueLocalCertificate",
			Handler:    _IdentityService_IssueLocalCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}

const (
	SecretService_StoreSecret_FullMethodName = "/ua_kernel.v1.SecretService/StoreSecret"
	SecretService_GetSecret_FullMethodName   = "/ua_kernel.v1.SecretService/GetSecret"
	SecretService_MountSecret_FullMethodName = "/ua_kernel.v1.SecretService/MountSecret"
	SecretService_ListSecrets_FullMethodName = "/ua_kernel.v1.SecretService/ListSecrets"
)

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretService manages secret storage and retrieval
type SecretServiceClient interface {
	// StoreSecret securely stores a secret
	StoreSecret(ctx context.Context, in *StoreSecretRequest, opts ...grpc.CallOption) (*StoreSecretResponse, error)
	// GetSecret retrieves a stored secret
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// MountSecret makes a secret available to a process
	MountSecret(ctx context.Context, in *MountSecretRequest, opts ...grpc.CallOption) (*MountSecretResponse, error)
	// ListSecrets returns metadata for available secrets
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
}

type secretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretServiceClient(cc grpc.ClientConnInterface) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) StoreSecret(ctx context.Context, in *StoreSecretRequest, opts ...grpc.CallOption) (*StoreSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_StoreSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) MountSecret(ctx context.Context, in *MountSecretRequest, opts ...grpc.CallOption) (*MountSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_MountSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, SecretService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
// All implementations must embed UnimplementedSecretServiceServer
// for forward compatibility.
//
// SecretService manages secret storage and retrieval
type SecretServiceServer interface {
	// StoreSecret securely stores a secret
	StoreSecret(context.Context, *StoreSecretRequest) (*StoreSecretResponse, error)
	// GetSecret retrieves a stored secret
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// MountSecret makes a secret available to a process
	MountSecret(context.Context, *MountSecretRequest) (*MountSecretResponse, error)
	// ListSecrets returns metadata for available secrets
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	mustEmbedUnimplementedSecretServiceServer()
}

// UnimplementedSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretServiceServer struct{}

func (UnimplementedSecretServiceServer) StoreSecret(context.Context, *StoreSecretRequest) (*StoreSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreSecret not implemented")
}
func (UnimplementedSecretServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretServiceServer) MountSecret(context.Context, *MountSecretRequest) (*MountSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountSecret not implemented")
}
func (UnimplementedSecretServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretServiceServer) mustEmbedUnimplementedSecretServiceServer() {}
func (UnimplementedSecretServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretServiceServer will
// result in compilation errors.
type UnsafeSecretServiceServer interface {
	mustEmbedUnimplementedSecretServiceServer()
}

func RegisterSecretServiceServer(s grpc.ServiceRegistrar, srv SecretServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretService_ServiceDesc, srv)
}

func _SecretService_StoreSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).StoreSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_StoreSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).StoreSecret(ctx, req.(*StoreSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_MountSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).MountSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_MountSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).MountSecret(ctx, req.(*MountSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretService_ServiceDesc is the grpc.ServiceDesc for SecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreSecret",
			Handler:    _SecretService_StoreSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "MountSecret",
			Handler:    _SecretService_MountSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretService_ListSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}

const (
	ClusterService_GetClusterState_FullMethodName      = "/ua_kernel.v1.ClusterService/GetClusterState"
	ClusterService_ProposeClusterConfig_FullMethodName = "/ua_kernel.v1.ClusterService/ProposeClusterConfig"
	ClusterService_JoinCluster_FullMethodName          = "/ua_kernel.v1.ClusterService/JoinCluster"
	ClusterService_GetKV_FullMethodName                = "/ua_kernel.v1.ClusterService/GetKV"
	ClusterService_PutKV_FullMethodName                = "/ua_kernel.v1.ClusterService/PutKV"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterService provides cluster state and coordination
type ClusterServiceClient interface {
	// GetClusterState retrieves current cluster state
	GetClusterState(ctx context.Context, in *GetClusterStateRequest, opts ...grpc.CallOption) (*GetClusterStateResponse, error)
	// ProposeClusterConfig proposes a configuration change
	ProposeClusterConfig(ctx context.Context, in *ProposeClusterConfigRequest, opts ...grpc.CallOption) (*ProposeClusterConfigResponse, error)
	// JoinCluster initiates cluster join ceremony
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
	// GetKV retrieves a value from cluster KV store
	GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error)
	// PutKV stores a value in cluster KV store
	PutKV(ctx context.Context, in *PutKVRequest, opts ...grpc.CallOption) (*PutKVResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetClusterState(ctx context.Context, in *GetClusterStateRequest, opts ...grpc.CallOption) (*GetClusterStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStateResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ProposeClusterConfig(ctx context.Context, in *ProposeClusterConfigRequest, opts ...grpc.CallOption) (*ProposeClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeClusterConfigResponse)
	err := c.cc.Invoke(ctx, ClusterService_ProposeClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, ClusterService_JoinCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKVResponse)
	err := c.cc.Invoke(ctx, ClusterService_GetKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) PutKV(ctx context.Context, in *PutKVRequest, opts ...grpc.CallOption) (*PutKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutKVResponse)
	err := c.cc.Invoke(ctx, ClusterService_PutKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
//
// ClusterService provides cluster state and coordination
type ClusterServiceServer interface {
	// GetClusterState retrieves current cluster state
	GetClusterState(context.Context, *GetClusterStateRequest) (*GetClusterStateResponse, error)
	// ProposeClusterConfig proposes a configuration change
	ProposeClusterConfig(context.Context, *ProposeClusterConfigRequest) (*ProposeClusterConfigResponse, error)
	// JoinCluster initiates cluster join ceremony
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
	// GetKV retrieves a value from cluster KV store
	GetKV(context.Context, *GetKVRequest) (*GetKVResponse, error)
	// PutKV stores a value in cluster KV store
	PutKV(context.Context, *PutKVRequest) (*PutKVResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) GetClusterState(context.Context, *GetClusterStateRequest) (*GetClusterStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedClusterServiceServer) ProposeClusterConfig(context.Context, *ProposeClusterConfigRequest) (*ProposeClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeClusterConfig not implemented")
}
func (UnimplementedClusterServiceServer) JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedClusterServiceServer) GetKV(context.Context, *GetKVRequest) (*GetKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKV not implemented")
}
func (UnimplementedClusterServiceServer) PutKV(context.Context, *PutKVRequest) (*PutKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutKV not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call pancis, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterState(ctx, req.(*GetClusterStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ProposeClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ProposeClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ProposeClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ProposeClusterConfig(ctx, req.(*ProposeClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_JoinCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_GetKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetKV(ctx, req.(*GetKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_PutKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).PutKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_PutKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).PutKV(ctx, req.(*PutKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterState",
			Handler:    _ClusterService_GetClusterState_Handler,
		},
		{
			MethodName: "ProposeClusterConfig",
			Handler:    _ClusterService_ProposeClusterConfig_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _ClusterService_JoinCluster_Handler,
		},
		{
			MethodName: "GetKV",
			Handler:    _ClusterService_GetKV_Handler,
		},
		{
			MethodName: "PutKV",
			Handler:    _ClusterService_PutKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}

const (
	ProviderService_InstallProvider_FullMethodName  = "/ua_kernel.v1.ProviderService/InstallProvider"
	ProviderService_StartProvider_FullMethodName    = "/ua_kernel.v1.ProviderService/StartProvider"
	ProviderService_StopProvider_FullMethodName     = "/ua_kernel.v1.ProviderService/StopProvider"
	ProviderService_GrantCapability_FullMethodName  = "/ua_kernel.v1.ProviderService/GrantCapability"
	ProviderService_RevokeCapability_FullMethodName = "/ua_kernel.v1.ProviderService/RevokeCapability"
	ProviderService_ListProviders_FullMethodName    = "/ua_kernel.v1.ProviderService/ListProviders"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderService manages capability provider lifecycle
type ProviderServiceClient interface {
	// InstallProvider downloads and stages a provider
	InstallProvider(ctx context.Context, in *InstallProviderRequest, opts ...grpc.CallOption) (*InstallProviderResponse, error)
	// StartProvider launches a provider process
	StartProvider(ctx context.Context, in *StartProviderRequest, opts ...grpc.CallOption) (*StartProviderResponse, error)
	// StopProvider terminates a provider process
	StopProvider(ctx context.Context, in *StopProviderRequest, opts ...grpc.CallOption) (*StopProviderResponse, error)
	// GrantCapability grants a capability to a provider
	GrantCapability(ctx context.Context, in *GrantCapabilityRequest, opts ...grpc.CallOption) (*GrantCapabilityResponse, error)
	// RevokeCapability revokes a capability from a provider
	RevokeCapability(ctx context.Context, in *RevokeCapabilityRequest, opts ...grpc.CallOption) (*RevokeCapabilityResponse, error)
	// ListProviders returns installed providers
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) InstallProvider(ctx context.Context, in *InstallProviderRequest, opts ...grpc.CallOption) (*InstallProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_InstallProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StartProvider(ctx context.Context, in *StartProviderRequest, opts ...grpc.CallOption) (*StartProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_StartProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StopProvider(ctx context.Context, in *StopProviderRequest, opts ...grpc.CallOption) (*StopProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_StopProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GrantCapability(ctx context.Context, in *GrantCapabilityRequest, opts ...grpc.CallOption) (*GrantCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantCapabilityResponse)
	err := c.cc.Invoke(ctx, ProviderService_GrantCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) RevokeCapability(ctx context.Context, in *RevokeCapabilityRequest, opts ...grpc.CallOption) (*RevokeCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCapabilityResponse)
	err := c.cc.Invoke(ctx, ProviderService_RevokeCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ProviderService manages capability provider lifecycle
type ProviderServiceServer interface {
	// InstallProvider downloads and stages a provider
	InstallProvider(context.Context, *InstallProviderRequest) (*InstallProviderResponse, error)
	// StartProvider launches a provider process
	StartProvider(context.Context, *StartProviderRequest) (*StartProviderResponse, error)
	// StopProvider terminates a provider process
	StopProvider(context.Context, *StopProviderRequest) (*StopProviderResponse, error)
	// GrantCapability grants a capability to a provider
	GrantCapability(context.Context, *GrantCapabilityRequest) (*GrantCapabilityResponse, error)
	// RevokeCapability revokes a capability from a provider
	RevokeCapability(context.Context, *RevokeCapabilityRequest) (*RevokeCapabilityResponse, error)
	// ListProviders returns installed providers
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) InstallProvider(context.Context, *InstallProviderRequest) (*InstallProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallProvider not implemented")
}
func (UnimplementedProviderServiceServer) StartProvider(context.Context, *StartProviderRequest) (*StartProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProvider not implemented")
}
func (UnimplementedProviderServiceServer) StopProvider(context.Context, *StopProviderRequest) (*StopProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProvider not implemented")
}
func (UnimplementedProviderServiceServer) GrantCapability(context.Context, *GrantCapabilityRequest) (*GrantCapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantCapability not implemented")
}
func (UnimplementedProviderServiceServer) RevokeCapability(context.Context, *RevokeCapabilityRequest) (*RevokeCapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCapability not implemented")
}
func (UnimplementedProviderServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_InstallProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).InstallProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_InstallProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).InstallProvider(ctx, req.(*InstallProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StartProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StartProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StartProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StartProvider(ctx, req.(*StartProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StopProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StopProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StopProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StopProvider(ctx, req.(*StopProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GrantCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GrantCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GrantCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GrantCapability(ctx, req.(*GrantCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_RevokeCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).RevokeCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_RevokeCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).RevokeCapability(ctx, req.(*RevokeCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua_kernel.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallProvider",
			Handler:    _ProviderService_InstallProvider_Handler,
		},
		{
			MethodName: "StartProvider",
			Handler:    _ProviderService_StartProvider_Handler,
		},
		{
			MethodName: "StopProvider",
			Handler:    _ProviderService_StopProvider_Handler,
		},
		{
			MethodName: "GrantCapability",
			Handler:    _ProviderService_GrantCapability_Handler,
		},
		{
			MethodName: "RevokeCapability",
			Handler:    _ProviderService_RevokeCapability_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _ProviderService_ListProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ua_kernel/v1/syscall.proto",
}
